### ISSUE TITLE
Unreleased studies are currently showing up on site search

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/SiteSearchData#12]
Currently on the live site - when we search for "SHINE" it returns the SHINE study page even though the SHINE study is not released yet. When one clicks on the SHINE study page it does return "page not found"

We also discovered that the same things happens for SIP and West Africa studies. 

Unreleased studies should not show up on site search results on the live site. 

<img width="1236" alt="Screen Shot 2022-07-05 at 3 07 53 PM" src="https://user-images.githubusercontent.com/62298921/177426139-5a537ce5-7e0f-487d-b3c5-711d42f2e5f0.png">

**Comment by iodice** [comment]
I checked in a fix for this. Once I update the filter fields, I'll dump a new batch of JSON.

**Comment by iodice** [comment]
This is fixed in dev sites (e.g. iodice.clinepidb.org)

**Comment by iodice** [comment]
This is fixed in QA
