### ISSUE TITLE
ClinEpi Site Search: update filter fields under "Studies"

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/SiteSearchData#13]
**Add `Data access records`, `study characteristics table`, `data accessibility level` fields**
Under "Studies", we should also be searching for:
1. Data Access Records table
2. Study characteristics table
3. Data accessibility (protected, controlled, etc.)

<img width="306" alt="Screen Shot 2022-07-01 at 3 14 30 PM" src="https://user-images.githubusercontent.com/67710160/176956548-54e0d90c-cb05-4769-9293-5d01f30b057d.png">

**Remove `Acknowledgement` and `Category` fields**
The "Acknowledgement" and "Category"  fields below always have a zero count. It is unclear what they are searching. They should be removed.

<img width="301" alt="Screen Shot 2022-07-01 at 3 11 05 PM" src="https://user-images.githubusercontent.com/67710160/176956113-27d12277-b1dd-4c03-943e-0ab41b73526c.png">

**Comment by iodice** [comment]
The new fields have been added. Making them appear in the "filter" list seems to be beyond the control of the site search model, so I'm assigning this to Steve.

**Comment by danicahelb** [comment]
as of 8/12 it looks like this:


![Image](https://user-images.githubusercontent.com/25450900/184419363-7ed5c3a6-77e0-4a8a-8304-df0a55f02a17.png)

**Comment by danicahelb** [comment]
@iodice we still need to remove "acknowledgement" and "category"

**Comment by iodice** [comment]
"Acknowledgement" and "category" are now gone.

**Comment by SheenaTomko** [comment]
This looks good!
