### ISSUE TITLE
Site search not searching "Study specific variable information" field

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/SiteSearchData#15]
I was looking for antibiotic resistance terms on qa.restricted.clinepidb.org with site search and searched for "resistance", and nothing was returned. The same search for “resistance” on the live site returned the "Azithromycin E-test" variable from ELICIT, which it matched based on "Study specific variable information" from the term definition. 

Based on this experience, it looks like site search on qa isn’t searching variable definitions, or maybe other similar fields like original variable name.

**Comment by danicahelb** [comment]
On the QA site, site search currently is only searching `Variable name` and `Category` fields. It is NOT searching the `Study specific variable information` table.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/25450900/184708140-33579c67-0d07-4608-873f-b50a07b9dde8.png">

On the live site, site search currently is searching `Variable name`, `Category`, and `Study specific variable information` fields (so the definition and original variable name are being searched).

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/25450900/184708243-d817dda8-64cc-4b6b-9cc0-65a724401918.png">

This is a bug. Please make sure to include the `Study specific variable information` field in site search

**Comment by iodice** [comment]
It turns out that Steve turned this off three months ago at the request, he recalls, of the clinepi team. He has followed up to check whether it's wanted. I now know how to put it back if it is.

**Comment by SheenaTomko** [comment]
This is fixed! Closing this ticket now :)
