### ISSUE TITLE
Site search: change "variable values" to "values"

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/SiteSearchData#22]
Feedback from both the ASTMH workshop & ClinEpi mini retreat was that the term "Variable values" in the left panel is confusing.

In the 12/2/22 EDA UX meeting, we decided that we will change the verbiage of "Variable values" to just "Values"

**Comment by iodice** [comment]
This has been changed in the model, and will show up on the QA site once the core is rebuilt.

**Comment by danicahelb** [comment]
This looks good on the QA site


![Image](https://user-images.githubusercontent.com/25450900/207437956-4784bc5e-2f92-4e01-82a7-122db43168d6.png)
