### ISSUE TITLE
Site search result goes to incorrect entity for a var

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/SiteSearchData#23]
qa.mbio -> site search -> search "habitat" -> click view in the Bonus study. That link goes here:
.../variables/EUPATH_0000096/ENVO_01000739
which gives the Cannot find specified variable error.

But, if i go to Bonus -> subset tab -> click Habitat, it works.
The url is now .../variables/EUPATH_0000609/ENVO_01000739

**Comment by dmfalke** [comment]
For what it's worth, the entity is incorrect from the site search service, so I moved this to the SiteSearchData repository.

**Comment by aurreco-uga** [comment]
seems to be working in prod site so closing
