### ISSUE TITLE
Site search: rename "Name" to "Study name"

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/SiteSearchData#6]
Seeing it in the list of fields on the left panel, I do think it would be better for "Name" to be labeled as "Study name"

<img width="251" alt="image" src="https://user-images.githubusercontent.com/25450900/174107959-ded47e03-9ced-4ae3-b91f-9aaf753887eb.png">

Also, in the tables for "Variables having this value" and "Study specific variable information", there is a column called "Study". Please rename this to "Study name" in both tables so that the terminology is used consistently 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/25450900/174188806-17cb253a-97cd-4133-a551-7cd60e8fc33b.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/25450900/174188873-a7aed5ce-cda2-4e71-9022-c3e4688ab493.png">

**Comment by iodice** [comment]
Steve Fischer reports that this can't be done currently, because the ClinEpiDB study record is shared with the dataset record of the genomics sites. He says it's something we'll have to live with until the two are unified, probably within a year.

**Comment by aurreco-uga** [comment]
ths seems addressed
