### ISSUE TITLE
ClinEpi Site Search: Change label & add tool tip or mouseover info to "Study specific variable information table" field 

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/SiteSearchData#7]
Under "Variables", we can filter on the field "Study specific variable information". It is hard for users to understand what is being search. Changing this term to `"Study specific variable information table"` will make it clear that all the information in the table is being searched.

<img width="1383" alt="Screen Shot 2022-07-01 at 3 27 55 PM" src="https://user-images.githubusercontent.com/67710160/176958093-63b9f014-1aa9-4937-8ed1-bbb77f6a7363.png">

Also, add a mouseover or tool tip to this term. Example of verbiage: `Searches the study name, entity, original variable name, and definition of the variable.`

<img width="306" alt="Screen Shot 2022-07-01 at 3 30 55 PM" src="https://user-images.githubusercontent.com/67710160/176958287-79de180c-67b1-4cfe-a7d7-c34197788ed3.png">

**Comment by dmfalke** [comment]
The tooltip will have to be done on the client. It might be worth considering making tooltip content a part of the model and including it in the site search service.

**Comment by danicahelb** [comment]
1. @dmfalke or @steve-fischer-200 please allow tooltip content to be a part of the model. 
2. @iodice please update the label & add mouseover verbiage
3. @dmfalke make front end changes to handle mouseover verbiage

**Comment by dmfalke** [comment]
It looks like "Study specific variable information" is no longer an option for filtering. I'm not sure if that was intentional. Assuming it was, then the only thing needed is to change the label to "Study specific variable information table", correct?


![image](https://user-images.githubusercontent.com/365139/184427407-9a61d6e5-3c5f-431d-aa1f-ef89553569db.png)

**Comment by iodice** [comment]
This is related to issue #15, which is on hold while the clinepi team decides whether the "Study specific variable information table" should be searchable.

If this table is included, it's not clear to me whether I have to make model changes to mae this tool tip show up. (I'll check with Dave.)

**Comment by dmfalke** [comment]
The tooltip will be hard coded in the front end code for now.

**Comment by dmfalke** [comment]
FYI, I have added the tooltip, so I think this issue can be closed and QA'd?

**Comment by danicahelb** [comment]
Looks great, thanks!


![Image](https://user-images.githubusercontent.com/25450900/187562242-412f86f4-7563-45b5-b729-441ced26ab3b.png)
