### ISSUE TITLE
Site search: reorder fields in the left panel

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/SiteSearchData#8]
Reorder filter fields in the left panel

The terms under **"Filter variable fields"** should have the following order:
1. Variable name
2. Study specific variable information table
3. Category

The terms under **Filter study fields** should have the following order (note, the fields for studies will be updated as part of https://github.com/VEuPathDB/SiteSearchData/issues/13):
1. Name (to be renamed Study name as per https://github.com/VEuPathDB/SiteSearchData/issues/6)
2. Summary
3. Description
4. Study characteristics
5. Data accessibility
6. Associated publications
7. Principle investigator and collaborators
8. Data Access Records

**Comment by steve-fischer-200** [comment]
They are ordered alphabetically.  Doing otherwise would be quite complicated to implement and maintain. @nkittur-uga

**Comment by danicahelb** [comment]
Discussed in 8/29/2022 EDA UX meeting.
@steve-fischer-200 confirmed that this request is a lot of work
ClinEpi team can live with the alphabetical ordering

Closing this ticket
